FROM debian:latest

EXPOSE 3306

RUN apt update; apt-get install mariadb-server -y;
RUN mkdir -p /var/run/mysqld; chown -R mysql:mysql /var/run/mysqld;

COPY tools/sql-conf.sh /home
COPY conf/50-server.cnf /etc/mysql/mariadb.conf.d/

RUN bash /home/sql-conf.sh

CMD ["mariadbd"]