FROM debian:latest

RUN apt update; apt install php7.4 php-mysqli php7.4-fpm -y
RUN apt install vim wget unzip -y

COPY conf/www.conf /etc/php/7.4/fpm/pool.d
COPY tools/script.sh /home

CMD ["bash", "/home/script.sh"]